//##############################################################################
//###############     This file has been generated by EDROOM     ###############
//##############################################################################
 
#include <public/edroom_glue.h>
 
 
//******************************************************************************
// include deployment edroom components
 
#include <public/ricuasw_iface_v1.h>
#include <public/rccepdmanager_iface_v1.h>
#include <public/rcctm_channelctrl_iface_v1.h>
#include <public/cchk_fdirmng_iface_v1.h>
#include <public/ccbkgtcexec_iface_v1.h>
 
#ifdef CONFIG_EDROOMBP_DEPLOYMENT_NEED_TASK
 
	CEDROOMSystemDeployment systemDeployment;
 
#endif
 
 
 
rtems_task Init (uint32_t arg){
 
	//uint32_t aux;
 
#ifndef CONFIG_EDROOMBP_DEPLOYMENT_NEED_TASK
 
	CEDROOMSystemDeployment systemDeployment;
 
#endif
 
	//aux = sizeof(systemDeployment) + sizeof(RICUASW) + sizeof(RCCEPDManager);
	//aux += sizeof(RCCTM_ChannelCtrl) +sizeof (CCHK_FDIRMng) + sizeof(CCBKGTCExec);

	RICUASW	ricuasw(1, 13, EDROOMprioHigh, 1024, systemDeployment.GetricuaswMemory());
	RCCEPDManager	rccepdmanager(2, 11, EDROOMprioHigh, 1024, systemDeployment.GetrccepdmanagerMemory());
	RCCTM_ChannelCtrl	rcctm_channelctrl(3, 10, EDROOMprioVeryHigh, 1024, systemDeployment.Getrcctm_channelctrlMemory());
	CCHK_FDIRMng	cchk_fdirmng(4, 14, EDROOMprioNormal, 8192, systemDeployment.Getcchk_fdirmngMemory());
	CCBKGTCExec	ccbkgtcexec(5, 11, EDROOMprioNormal, 8192, systemDeployment.GetccbkgtcexecMemory());
 
	systemDeployment.Config(&ricuasw, &rccepdmanager, &rcctm_channelctrl, &cchk_fdirmng, &ccbkgtcexec);
 
	systemDeployment.Start();
 
	;
 
}
